/// Generated by AssetsRefGenerator on 2020/04/22
class Res {
  static const String mp31 = "audios/1.mp3";
  static const String mp32 = "audios/2.mp3";
  static const String mp33 = "audios/3.mp3";
  static const String mp34 = "audios/4.mp3";
  static const String mp35 = "audios/5.mp3";
  static const String mp36 = "audios/6.mp3";
  static const String caomp3 = "audios/cao.mp3";
  static const String gatomp3 = "audios/gato.mp3";
  static const String leaomp3 = "audios/leao.mp3";
  static const String macacomp3 = "audios/macaco.mp3";
  static const String ovelhamp3 = "audios/ovelha.mp3";
  static const String vacamp3 = "audios/vaca.mp3";
  //static const String  = "assets/imagens/.DS_Store";
  static const String png1 = "assets/imagens/1.png";
  static const String png2 = "assets/imagens/2.png";
  static const String png3 = "assets/imagens/3.png";
  static const String png4 = "assets/imagens/4.png";
  static const String png5 = "assets/imagens/5.png";
  static const String png6 = "assets/imagens/6.png";
  static const String pngcao = "assets/imagens/cao.png";
  static const String pngdireitos = "assets/imagens/direitos.png";
  static const String pnggato = "assets/imagens/gato.png";
  static const String pngleao = "assets/imagens/leao.png";
  static const String pngmacaco = "assets/imagens/macaco.png";
  static const String pngovelha = "assets/imagens/ovelha.png";
  static const String jpgsegundo_fundo = "assets/imagens/segundo_fundo.jpg";
  static const String pngsegundo_fundo = "assets/imagens/segundo_fundo.png";
  static const String pngvaca = "assets/imagens/vaca.png";
}
